### PR TITLE
Version checking for kdialog formatting

### LINKED ISSUE #41: Dialog box text formatted incorrectly?
So I tried this out on KDE on Wayland and doing a basic message dialog no matter what I put in for the message it's malformed:
image

message code
```
MessageDialog::new()
      .set_type(MessageType::Error)
      .set_title("Fatal Error")
      .set_text(msg)
      .show_alert()
      .unwrap();
```

### PR DESCRIPTION
**Pull request by CorneliusCornbread**
Adds check to kdialog backend to change the formatting style depending on the version of kdialog. Fixes #41 

- [x] Parsing version string
- [ ] Find correct version to implement old formatting for

### CODE REVIEW

**Comment by CorneliusCornbread** [comment]
Did not mean to merge this, VSCode decided it was time to pull a funny.

**Comment by CorneliusCornbread** [comment]
@balthild I'm unable to revert this PR for some reason, it appears I may not have write permissions on this repo?

**Comment by balthild** [comment]
It's strange. I cannot revert it too...

image

**Comment by balthild** [comment]
image

Well, OK...

**Comment by CorneliusCornbread** [comment]
> image
> 
> Well, OK...

Yeah VSCode for some reason thought me pushing my one change also meant I wanted to merge. I apologize, that's my fault.

I can roll back the change and make a PR to do so, or we can roll with it, since currently the only thing that hasn't been fully addressed is the exact version that is problematic. If we roll with it the only thing that needs changing is the version that is tested for.

**Pull request merged**
